app:
  name: kaelthas



spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

APP_HOME: ${APP_HOME}

#DATA config
DATA_HOME: ${user.home}/tiklab/kaelthas

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/kaelthas?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: kaelthas
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs config
dcs:
  server:
    enabled: true
    #    enabled: false
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    #    url: 127.0.0.1:5035
    group: g1
    database: dcs1
    expire: 7200



# (local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: ""



