app:
  name: tiklab-kaelthas-ce
  version: ee

APP_HOME: ${APP_HOME}
application: kaelthas-ce

spring:
  config:
    import: optional:classpath:/config/${env:dev}/application.yaml
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/xmonitor_ee?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/thoughtware/xmonitor-ee

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}


#dcs config
dcs:
  server:
    enabled: true
    #    enabled: false
    port: 5020
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5020
    #    url: 127.0.0.1:5035
    group: g1
    database: dcs1
    expire: 7200

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

postgresql:
  embbed:
    enable: true
  database: xmonitor_ee
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

datapath: ${DATA_HOME}/caches

soular:
  embbed:
    enable: true
  address: e.tiklab.net


backups:
  dir: /data/xmonitor-ee
  #    time: 0 */1 * * * ?
  time: 0 0 2 * * ?

#message:
#  sms:
#    enabled: true

#base:
#  url: http://xmonitor-ce.test.tiklab.net/

#homes
homes:
  address: http://homes.tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net