app:
  name: kaelthas

APP_HOME: ${APP_HOME}
application: kaelthas

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5000/xmonitor_ee?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
DATA_HOME: /opt/tiklab/xmonitor-ee

plugin:
  path: ${DATA_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${DATA_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${DATA_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

postgresql:
  embbed:
    enable: true
  database: matflow_ee
  db:
    port: 5000
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

datapath: ${DATA_HOME}/caches

eas:
  embbed:
    enable: false
  address: http://eas-ee.demo.tiklab.net


backups:
  dir: /data/xmonitor-ee
  #    time: 0 */1 * * * ?
  time: 0 0 2 * * ?

#message:
#  sms:
#    enabled: true

base:
  url: http://xmonitor-ee.demo.tiklab.net

#homes
homes:
  address: http://tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net












