app:
  name: kaelthas


server:
  port: 8080

APP_HOME: ${APP_HOME}

#DATA config
DATA_HOME: ${user.home}/tiklab/kaelthas

#dal config for mysql jdbc
jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/kaelthas?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: true
  database: kaelthas
  db:
    port: 5432
    username: postgres
    password: darth2020
    address: ${DATA_HOME}/postgresql

#dcs config
dcs:
  server:
    enabled: true
    mode: server
    port: 5000
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}


# (local:本地登录  soular:统一登录)
auth:
  type: soular
  soular:
    address: http://e.eas.tiklab.net
  expire: 86400 # 过期时间，单位秒，默认1天

#backups:
#  dir: /data/xmonitor-ee
#  time: 0 0 2 * * ?

external:
  url: http://e.kaelthas.tiklab.net




