app:
  name: kaelthas-ce

server:
  port: 8020

APP_HOME: ${APP_HOME}

DATA_HOME: ${user.home}/tiklab/${app.name}

jdbc:
  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://172.13.1.27:5432/xmonitor_ee?stringtype=unspecified
  #  url: jdbc:postgresql://172.10.1.10:5432/throughtware_xmonitor_ce?stringtype=unspecified
  url: jdbc:postgresql://172.10.1.10:5432/tiklab-kaelthas?stringtype=unspecified
  #url: jdbc:postgresql://172.10.1.10:5432/tiklab-kaelthas-test?stringtype=unspecified
  username: postgres
  password: darth2020

postgresql:
  embbed:
    enable: false
  database: tiklab_xmonitor
  type: local

#dcs config
dcs:
  server:
    enabled: true
    port: 5030
    datapath: ${DATA_HOME}/caches
  client:
    url: 127.0.0.1:5030
    group: g1
    database: dcs1
    expire: 7200



# (local:本地登录  soular:统一登录)
auth:
  type: local
  soular:
    address: "http://192.168.10.15:8080"
  expire: 86400 # 过期时间，单位秒，默认1天


external:
  url: http://192.168.10.24:8080


