INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('8', 'systems.cpu.hard', 'CPU', 6, '用户空间进程的CPU的调度优先级', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('16', 'systems.host.beginTime', 'host', 2, '主机的开始运行的时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('21', 'systems.internet.readPackage', 'internet', 2, '获取网络读写字节包个数', 2);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('25', 'systems.memory.free', 'memory', 5, '完全空闲中的内存', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('23', 'systems.memory.used', 'memory', 3, '已用内存', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('24', 'systems.memory.available', 'memory', 4, '剩余可用内存', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('10', 'systems.memory.percent', 'memory', 1, '内存使用率', 1);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('18', 'systems.cpu.load5', 'CPU', 11, 'CPU五分钟内的平均负载', 6);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('19', 'systems.cpu.load15', 'CPU', 12, 'CPU十五分钟内的平均负载', 6);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('17', 'systems.cpu.load1', 'CPU', 10, 'CPU一分钟内的平均负载', 6);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('7', 'systems.cpu.idleTime', 'CPU', 5, 'CPU处于空闲状态时间', 5);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('11', 'systems.cpu.irqTime', 'CPU', 8, '处理硬中断的 CPU 时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('27', 'systems.host(ip,port)', 'host', 4, '测试端口是否启动', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('26', 'systems.host(host,isuse)', 'host', 5, '主机是否可用', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('13', 'systems.cpu.logicNumber', 'CPU', 13, 'CPU逻辑核数', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('14', 'systems.cpu.physicsNumber', 'CPU', 14, 'CPU物理核数', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('9', 'systems.cpu.readWriteTime', 'CPU', 7, 'IO读写操作导致CPU处于等待状态的时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('6', 'systems.cpu.rate', 'CPU', 4, 'CPU利用率', 1);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('3', 'systems.cpu.systemTime', 'CPU', 3, 'CPU系统占用时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('2', 'systems.cpu.userTime', 'CPU', 2, '用户态进程占用CPU时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('12', 'systems.cpu.softirq', 'CPU', 9, '处理软中断的 CPU 时间', 4);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('28', 'systems.io.total(path)', 'IO', 3, '磁盘总量', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('29', 'systems.io.used(path)', 'IO', 4, '磁盘使用量', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('30', 'systems.io.avail(path)', 'IO', 5, '空闲磁盘', 3);
INSERT INTO "public"."mtc_item" ("id", "name", "data_categories", "data_type", "data_subclass", "report_type") VALUES ('5', 'systems.io.usedPercent(path)', 'IO', 1, '磁盘使用率', 1);

INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('103', 'systems.mysql.UpdatedRowsTrend', '每秒修改行数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('105', 'systems.mysql.ReturnedRowsTrend', '返回行数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('106', 'systems.mysql.RolledBackTransactionsTrend', '每秒回滚事务数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('107', 'systems.mysql.CommittedTransactionsTrend', '每秒提交事务数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('108', 'systems.mysql.ConflictsTrend', '事务冲突数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('109', 'systems.mysql.CacheHitRate', '缓存命中率', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('110', 'systems.mysql.ActiveSessions', '活动会话数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('111', 'systems.mysql.IdleSessions', '空闲会话数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('112', 'systems.mysql.DeadlocksTrend', '僵直趋势', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('113', 'systems.mysql.TemporaryFilesTrend', '临时文件趋势', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('114', 'systems.mysql.Locks', '锁数量', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('104', 'systems.mysql.FetchedRowsTrend', '每秒读取行数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('102', 'systems.mysql.DeletedRowsTrend', '每秒删除行数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('101', 'systems.mysql.InsertedRowsTrend', '每秒插入行数', 1, 'MYSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('3', 'systems.db.UpdatedRowsTrend', '每秒修改行数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('5', 'systems.db.ReturnedRowsTrend', '返回行数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('6', 'systems.db.RolledBackTransactionsTrend', '每秒回滚事务数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('7', 'systems.db.CommittedTransactionsTrend', '每秒提交事务数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('8', 'systems.db.ConflictsTrend', '事务冲突数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('9', 'systems.db.CacheHitRate', '缓存命中率', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('10', 'systems.db.ActiveSessions', '活动会话数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('11', 'systems.db.IdleSessions', '空闲会话数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('12', 'systems.db.DeadlocksTrend', '僵直趋势', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('13', 'systems.db.TemporaryFilesTrend', '临时文件趋势', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('14', 'systems.db.Locks', '锁数量', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('4', 'systems.db.FetchedRowsTrend', '每秒读取行数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('2', 'systems.db.DeletedRowsTrend', '每秒删除行数', 1, 'PostgreSQL');
INSERT INTO "public"."mtc_db_item" ("id", "expression", "describe", "data_type", "db_type") VALUES ('1', 'systems.db.InsertedRowsTrend', '每秒插入行数', 1, 'PostgreSQL');


INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('4', 'k8s_cluster_statefulset_total', 'Statefulset 的数量', 'cluster', 1, 'Statefulset Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('208', 'k8s_service_pod_memory_usage', 'Pod 的内存资源总使用量(未开发)', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('209', 'k8s_service_pod_status_waiting', '当前处于等待状态的 Pod 和容器，并显示原因(未开发)', 'service', 2, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('210', 'k8s_service_pod_status_terminated', '当前处于终止状态的 Pod 和容器，并显示原因(未开发)', 'service', 2, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('211', 'k8s_service_pod_status_restarts_total', '与 Pod 相关的每个容器重启次数(未开发)', 'service', 2, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('202', 'k8s_service_pod_status', 'Pod 的当前状态', 'service', 2, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('2', 'k8s_cluster_namespace_total', '命名空间的数量', 'cluster', 1, 'Namespace Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('1', 'k8s_cluster_node_total', '节点数', 'cluster', 1, 'Node Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('7', 'k8s_cluster_pod_total', 'Pod数量', 'cluster', 1, 'Pod Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('201', 'k8s_service_pod_total', 'Pod 数量', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('203', 'k8s_service_cpu_cores_requests', '此服务的 CPU 资源请求', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('204', 'k8s_service_cpu_cores_limits', '此服务的 CPU 资源限制', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('205', 'k8s_service_memory_requests', '此服务的内存资源请求', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('206', 'k8s_service_memory_limits', '此服务的内存资源限制', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('114', 'k8s_node_memory_usage', '节点总内存使用量(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('104', 'k8s_node_cpu_cores_requests', '节点中Pod的CPU请求总数(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('105', 'k8s_node_cpu_cores_limits', '节点中Pod的CPU限制总数(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('108', 'k8s_node_memory_requests', '节点中所有 Pod 的内存请求总量(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('109', 'k8s_node_memory_limits', '节点中所有 Pod 的内存限制总量(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('207', 'k8s_service_pod_cpu_usage', 'Pod 的 CPU 资源总使用量(未开发)', 'service', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('113', 'k8s_node_cpu_usage', '节点CPU 核心的总使用量(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('107', 'k8s_node_memory_total', '节点总内存量', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('116', 'k8s_node_network_transmit', '节点网络发送(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('115', 'k8s_node_network_receive', '节点网络接收(未开发)', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('8', 'k8s_cluster_container_total', 'Container数量', 'cluster', 1, 'Container Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('6', 'k8s_cluster_service_total', 'Service数量', 'cluster', 1, 'Service Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('5', 'k8s_cluster_daemonset_total', 'DaemonSet的数量', 'cluster', 1, 'DaemonSet Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('3', 'k8s_cluster_deployment_total', 'deployment数量', 'cluster', 1, 'Deployment Total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('21', 'k8s_cluster_service_pod_status', 'Service Pod Status', 'cluster', 2, 'Service Pod Status');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('20', 'k8s_cluster_deployment_status', 'Deployment Status', 'cluster', 2, 'Deployment Status');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('19', 'k8s_cluster_node_status', 'Node Status', 'cluster', 2, 'Node Status');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('18', 'k8s_cluster_storage_allocatable', '集群中所有节点的可分配存储容量', 'cluster', 3, 'storage_allocatable');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('13', 'k8s_cluster_memory_total', '集群中所有节点的总内存量', 'cluster', 3, 'memory_total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('17', 'k8s_cluster_storage_total', '集群中所有节点的总存储容量', 'cluster', 3, 'storage_total');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('16', 'k8s_cluster_memory_allocatable', '集群中可分配的内存量', 'cluster', 3, 'memory_allocatable');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('15', 'k8s_cluster_memory_limits', '集群中所有 Pod 的内存限制总量', 'cluster', 3, 'memory_limits');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('14', 'k8s_cluster_memory_requests', '集群中所有 Pod 的内存请求总量', 'cluster', 3, 'memory_requests');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('9', 'k8s_cluster_cpu_cores', '集群中的总CPU核心数', 'cluster', 3, 'cpu_cores');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('10', 'k8s_cluster_cpu_cores_requests', '集群中所有Pod的CPU请求总数', 'cluster', 3, 'cpu_cores_requests');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('11', 'k8s_cluster_cpu_cores_limits', '集群中所有Pod的CPU限制总数', 'cluster', 3, 'cpu_cores_limits');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('12', 'k8s_cluster_cpu_cores_allocatable', '集群中可分配的CPU核心数', 'cluster', 3, 'cpu_cores_allocatable');
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('101', 'k8s_node_pod_total', '此节点中的 pod 数量', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('102', 'k8s_node_node_status', '该节点的当前状态', 'node', 2, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('103', 'k8s_node_cpu_cores', '节点总CPU核心数', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('106', 'k8s_node_cpu_cores_allocatable', '节点中可分配的CPU核心数', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('112', 'k8s_node_storage_allocatable', '节点中可分配存储容量', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('110', 'k8s_node_memory_allocatable', '节点中可分配的内存量', 'node', 1, NULL);
INSERT INTO "public"."mtc_ku_item" ("id", "expression", "describe", "kubernetes_type", "report_type", "name") VALUES ('111', 'k8s_node_storage_total', '节点总存储容量', 'node', 1, NULL);


INSERT INTO "public"."mtc_internet_item" ("id", "name", "expression", "describe", "internet_type", "report_type", "is_optional") VALUES ('303', 'outOctets', 'kaelthas.internet.outOctets', '下行流量', 1, 1, 1);
INSERT INTO "public"."mtc_internet_item" ("id", "name", "expression", "describe", "internet_type", "report_type", "is_optional") VALUES ('302', 'inOctets', 'kaelthas.internet.inOctets', '上行流量', 1, 1, 1);
INSERT INTO "public"."mtc_internet_item" ("id", "name", "expression", "describe", "internet_type", "report_type", "is_optional") VALUES ('301', 'pod status', 'kaelthas.internet.podStatus', '端口状态', 1, 2, 1);


INSERT INTO "mtc_medium" ("id", "name", "type", "status", "details") VALUES ('1', 'APP', 1, 1, '通过APP告警');
INSERT INTO "mtc_medium" ("id", "name", "type", "status", "details") VALUES ('2', '企业微信', 2, 1, '通过企业微信发送告警信息');
INSERT INTO "mtc_medium" ("id", "name", "type", "status", "details") VALUES ('3', '站内信', 3, 1, '通过钉钉发送告警信息');
INSERT INTO "mtc_medium" ("id", "name", "type", "status", "details") VALUES ('4', '邮件通知', 4, 1, '通过邮件通知');

INSERT INTO "mtc_host_group" ("id", "name", "describe") VALUES ('977828517d01', '默认主机组', '默认主机组');

INSERT INTO "mtc_host" ("id", "name", "ip", "host_group_id", "state", "usability", "describe", "create_time", "update_time", "visibility", "color") VALUES ('9b426a2acd9e', '默认主机', '127.0.0.1', '977828517d01', 1, 0, NULL, '2024-06-24 16:43:12', NULL, NULL, 4);